# Generated by Django 5.1.6 on 2025-03-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('shown', 'Shown'), ('closed', 'Closed'), ('clicked', 'Clicked'), ('auto_closed', 'Auto Closed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=5000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbails', models.ImageField(blank=True, null=True, upload_to='app_thumbnails')),
                ('category', models.CharField(blank=True, choices=[('DAW', 'DAWs'), ('Plugins', 'Plugins'), ('Sample', 'Sample'), ('library', 'Library & Expansions')], max_length=5000, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='app_videos/')),
                ('video_size', models.FloatField(default=0)),
                ('youtube_link', models.URLField(blank=True, max_length=5000, null=True)),
                ('youtube_duration', models.DurationField(blank=True, null=True)),
                ('youtube_comments_count', models.PositiveIntegerField(default=0)),
                ('youtube_views_count', models.PositiveIntegerField(default=0)),
                ('youtube_thumbnails', models.JSONField(blank=True, null=True)),
                ('app_file', models.FileField(blank=True, null=True, upload_to='app_files/')),
                ('google_drive_link', models.URLField(blank=True, max_length=5000, null=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
